[project]
authors = ["Horned_Axe <horned_axe@proton.me>"]
channels = ["nvidia", "conda-forge", "pytorch"]
description = "Add a short description here"
name = "CosyVoice"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.8.*"
pynini = "2.1.5.*"
setuptools = "*"
cuda = {version = "*", channel = "nvidia"}
pytorch = {version = "2.0.1", channel = "pytorch"}
torchaudio = {version = "2.0.2", channel = "pytorch"}
pytorch-cuda = {version = "*", channel = "pytorch"}
mkl = "2024.0"

[pypi-dependencies]
conformer = "==0.3.2"
diffusers = "==0.27.2"
gdown = "==5.1.0"
gradio = "==4.32.2"
grpcio = "==1.57.0"
grpcio-tools = "==1.57.0"
huggingface-hub = "==0.23.5"
hydra-core = "==1.3.2"
HyperPyYAML = "==1.2.2"
inflect = "==7.3.1"
librosa = "==0.10.2"
lightning = "==2.2.4"
matplotlib = "==3.7.5"
modelscope = "==1.15.0"
networkx = "==3.1"
omegaconf = "==2.3.0"
onnx = "==1.16.0"
openai-whisper = "==20231117"
protobuf = "==4.25"
pydantic = "==2.7.0"
rich = "==13.7.1"
soundfile = "==0.12.1"
tensorboard = "==2.14.0"
uvicorn = "==0.30.0"
wget = "==3.2"
fastapi = "==0.111.0"
fastapi-cli = "==0.0.4"
WeTextProcessing = "==1.0.3"
transformers = "*"

ttsfrd = {path="./pretrained_models/CosyVoice-ttsfrd/ttsfrd-0.3.6-cp38-cp38-linux_x86_64.whl"}

[target.linux-64.pypi-dependencies]
deepspeed = "==0.14.2"
onnxruntime-gpu = "==1.16.0"
